Restaurant card updates w/ favorites post functionality
HR-BlueOcean-SpiritedAway/Rumble pull request #26
Opened 2022-05-12 17:57 UTC by garofalof

2022-05-12 18:35 UTC, dennisrcao approved these changes

2022-05-12 18:35 UTC, dennisrcao commented on components/RestaurantDetail.js
> +        <ToggleSwitch />
doesn't adding Toggleswitch skew from the mockup Edgar provided?

2022-05-12 19:54 UTC, jakemgilfix commented on components/RestaurantDetail.js
> +      setIsActive((prev)=>!prev);
Need to remove the restaurant from a user's favorites list.

2022-05-12 19:55 UTC, jakemgilfix requested changes
Should probably quickly add a route to remove a restaurant from a user's favorites list before we move on and forget to fix it.

2022-05-12 20:04 UTC, DongHyoungKim approved these changes

2022-05-13 00:00 UTC, jakemgilfix approved these changes

2022-05-13 00:01 UTC, merged